### ISSUE TITLE
New release incl. Cyp1a2 cyp2c19 data

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Database-for-observed-data#24]
@Yuri05 @sfrechen 

As the PR https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/pull/22 has been merged, the 'master'  branch contains the data for CYP1A2 and CYP2C19 networks. Could you create a new release so I can use it in the qualification plans (here https://github.com/Open-Systems-Pharmacology/Qualification-DDI-CYP1A2 and here https://github.com/Open-Systems-Pharmacology/Qualification-DDI-CYP2C19)? Or how should I proceed?

**Comment by sfrechen** [comment]
@PavelBal 
We are going to release v1.3 soon. We can add your additional data as well if you could include it by the end of the week.

**Comment by Yuri05** [comment]
I assume this issue is fixed?

**Comment by PavelBal** [comment]
Well, it's not released yet, but will be part of the next one and can already be referenced in qualification plans, so cal close.
