### ISSUE TITLE
Function"getAverage" used in convert_XLS_to_JSON

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Database-for-observed-data#25]
Trying to execute the code, the function "getAverage" cannot be found. From which package does it come?

@sfrechen

**Comment by sfrechen** [comment]
@PavelBal 

It is part of "auxiliaryFunctions.R" which is sourced at the beginning:
`source(file.path("code","auxiliaryFunctions.R"))`
