### ISSUE TITLE
Replace the DDI mechanism "Competitive_Inhibition" by "Reversible_Inhibition"

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Database-for-observed-data#29]
To include various types of reversible inhibition in one group for plotting, the suggested naming is preferred.

**Comment by Yuri05** [comment]
@sfrechen is it fixed now?

**Comment by sfrechen** [comment]
https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/commit/0162247fd5a5c8947873ebef5aa19991cdcb5f9e fixes #29
