### ISSUE TITLE
Complete information on selected studies in Studies, DDI and Projects sheet

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Database-for-observed-data#36]
@PavelBal

Please complete information for the following studies in the Sheets `Studies`, `DDI` and `Projects`

| ID   | Study               | Reference                                 |
| ---- | ------------------- | ----------------------------------------- |
| 6010 | Yasui-Furukori 2004 | https://pubmed.ncbi.nlm.nih.gov/15025747/ |
| 6011 | Yasui-Furukori 2004 | https://pubmed.ncbi.nlm.nih.gov/15025747/ |
| 6020 | Cho 2002            | https://pubmed.ncbi.nlm.nih.gov/11966672/ |
| 6021 | Cho 2002            | https://pubmed.ncbi.nlm.nih.gov/11966672/ |
| 6030 | Yao 2003            | https://pubmed.ncbi.nlm.nih.gov/12695344/ |
| 6031 | Yao 2003            | https://pubmed.ncbi.nlm.nih.gov/12695344/ |
| 6032 | Yao 2003            | https://pubmed.ncbi.nlm.nih.gov/12695344/ |
| 6040 | Yu 2001             | https://pubmed.ncbi.nlm.nih.gov/11309556/ |
| 6050 | Granfors 2005       | https://pubmed.ncbi.nlm.nih.gov/16198659/ |
| 6060 | Jeppesen 1996       | https://pubmed.ncbi.nlm.nih.gov/8807660/  |
| 6061 | Culm-Merdek 2005    | https://pubmed.ncbi.nlm.nih.gov/16236038/ |
| 6070 | Granfors 2004       | https://pubmed.ncbi.nlm.nih.gov/14998432/ |
| 6080 | Joeres 1987         | https://pubmed.ncbi.nlm.nih.gov/3628469/  |
| 6090 | Momo 2010           | https://pubmed.ncbi.nlm.nih.gov/19789372/ |
| 6100 | Kusumoto 2001       | https://pubmed.ncbi.nlm.nih.gov/11240973/ |
| 6110 | Balogh 1995         | https://pubmed.ncbi.nlm.nih.gov/7589032/  |

**Comment by sfrechen** [comment]
How about the empty one? :)

`Studies` Column G to L, Nto BR
`DDI`  Column I, L to N, P to R, X, Y. AD to AP
`Projects` Column G

Please feel to be inspired by existing IDs.

**Comment by PavelBal** [comment]
Are they all really **required**? I can only do the minimal requirements for the acceptance.

**Comment by sfrechen** [comment]
Technically, they are not necessarily all required. But the vision of the database is to serve as more than a technical background. Furthermore, we plan on more direct links between PK-Sim and the database. More and more information could become technically relevant. So please add the information which is available from the papers. Missing information obviously cannot be added...

Additionally, I do not understand why none of them has concentration time profiles. This is pretty unusual for DDI studies. To generate JSON files from the `PK-Profiles` sheet, some of the empty fiels are indeed required.

**Comment by StephanSchaller** [comment]
Sorry, @sfrechen, but if there are technical requirements and "nice to have" entries, these need to be specified explicitly.
From earlier discussions only some very specific entries were required, and if this is urgent (and I guess everyone would like to have the new models also released) we should focus on these.
Can you please provide a list of absolutely required entries?

**Comment by sfrechen** [comment]
Sorry, @StephanSchaller and @PavelBal , I do not get the point. We have defined certain quality standards which we should adhere to. I cannot understand that the few data points are still not there. Technically, I already fixed most issues to make the DDI sheet run. Missing is here is only the column `Mechanism`.

By the way: I also merged your PR. There is no acceptance pending! Please simply try to adhere to the quality standards (the issue is marked as enhancement not as bug...) 
Also, what about all the CT profiles? When can we expect them to be added?

**Comment by PavelBal** [comment]
I don't know how to save the DDI.csv separated by semicolons.
