### ISSUE TITLE
DDI.csv is broken

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Database-for-observed-data#53]
When trying to use the current DDI.csv within the reporting engine, an error is thrown:

```
Error using readtable (line 216)
Reading failed at line 248. All lines of a text file must have the same number of delimiters. Line 248 has 34 delimiters, while preceding lines have 41.
```

Looking at the csv, there is a newline entry in a data set:

![image](https://user-images.githubusercontent.com/25903040/166236915-09ea7fad-c383-4eb3-90d2-f9fb071549dc.png)
 coming from a cell with a new line in excel:

![image](https://user-images.githubusercontent.com/25903040/166237066-4cb2ecef-b543-4f03-ba00-bdf65044025f.png)

Please fix ASAP, I cannot fix it on my own as my systems locale csv export ist with `,` as delimiter and not `;`.

**Comment by PavelBal** [comment]
@Yuri05 @AndreDlm

**Comment by AndreDlm** [comment]
Hmm this newline entry does not come from me, must be in there for some time now, but I can fix it...
