### ISSUE TITLE
Provide description for the new release

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Database-for-observed-data#55]
New Release (1.4) just created (as prerelease). https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/releases/tag/v1.4
Please provide the **description** for the release.

**Comment by PavelBal** [comment]
- Added time-concentration data for evaluation:
  - [Ethinylestradiol](https://github.com/Open-Systems-Pharmacology/Ethinylestradiol-Model)
  - [Fluvoxamine](https://github.com/Open-Systems-Pharmacology/Fluvoxamine-Model/tree/cyp1a2_cyp2C19_DDI)
  - [Mexiletine](https://github.com/Open-Systems-Pharmacology/Mexiletine-Model)
  - [Moclobemide](https://github.com/Open-Systems-Pharmacology/Moclobemide-Model)
  - [Omeprazole](https://github.com/Open-Systems-Pharmacology/Omeprazole-Model)
  - [S-Mephenytoin](https://github.com/Open-Systems-Pharmacology/S-Mephenytoin-Model)
  - [Tizanidine](https://github.com/Open-Systems-Pharmacology/Tizanidine-Model)
- Added time-concentration and DDI ratios data for DDI scenarios:
  - [Ethinylestradiol-Caffeine-DDI](https://github.com/Open-Systems-Pharmacology/Ethinylestradiol-Caffeine-DDI)
  - [Ethinylestradiol-Tizanidine-DDI](https://github.com/Open-Systems-Pharmacology/Ethinylestradiol-Tizanidine-DDI)
  - [Fluvoxamine-Caffeine-DDI](https://github.com/Open-Systems-Pharmacology/Fluvoxamine-Caffeine-DDI/tree/Fluvoxamine-Caffeine-DDI_CYP1A2)
  - [Fluvoxamine-Mexiletine-DDI](https://github.com/Open-Systems-Pharmacology/Fluvoxamine-Mexiletine-DDI)
  - [Fluvoxamine-Omeprazole-DDI](https://github.com/Open-Systems-Pharmacology/Fluvoxamine-Omeprazole-DDI)
  - [Fluvoxamine-S-mephenytoin-DDI](https://github.com/Open-Systems-Pharmacology/Fluvoxamine-S-mephenytoin-DDI)
  - [Fluvoxamine-Tizanidine-DDI](https://github.com/Open-Systems-Pharmacology/Fluvoxamine-Tizanidine-DDI)
  - [Mexiletine-Caffeine-DDI](https://github.com/Open-Systems-Pharmacology/Mexiletine-Caffeine-DDI)
  - [Mexiletine-Tizanidine-DDI](https://github.com/Open-Systems-Pharmacology/Mexiletine-Tizanidine-DDI)
  - [Moclobemide-Omeprazole-DDI](https://github.com/Open-Systems-Pharmacology/Moclobemide-Omeprazole-DDI)

**Comment by Yuri05** [comment]
@PavelBal Thx! Added to the release description.

**Comment by AndreDlm** [comment]
In addition to that:
* Adds additional time-concentration data for evaluation for carbamazepine
* Adds additional time-concentration and DDI ratios data for Erythromycin-Carbamazepine-DDI

**Comment by Yuri05** [comment]
@AndreDlm Thx! Added.
