### ISSUE TITLE
Unknown average type

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Database-for-observed-data#60]
When running the [R script](https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/blob/master/code/convert_XLS_to_JSON.R) for the database I get the following error message:
![image](https://user-images.githubusercontent.com/26541603/167672838-26a78005-dbef-4644-8b5e-51ac809a0f39.png)

Some lines have the average type `Mean` which is not accepted by the R script:
![image](https://user-images.githubusercontent.com/26541603/167673490-21b203fd-3dfc-4a9b-8797-2b1f6afe0c65.png)

The allowed types are defined in the [data item specification list](https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/blob/master/obsDataPK_OSP_DISL.docx)

**Comment by Yuri05** [comment]
fixed with #62
