### ISSUE TITLE
Pediatrics.csv corrupted

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Database-for-observed-data#67]
In some records part was moved to the next line.

I really wonder why RE did not crash before. Now it does.

![grafik](https://user-images.githubusercontent.com/25061876/176912064-9875604c-5878-4fdf-8374-68162426b3c5.png)

**Comment by Yuri05** [comment]
I also wonder why it worked before. 
What I could imagine: all those illegal new lines in the file occur **within a string in double quotes**. I guess some CSV reader would consider everything between opening and closing double quotes as a single value, **even if there is a newline in between**. Some CSV reader will read only till the end of the line and produce an error in such a case, becasue they cannot find the closing double quotes. The latter happens now in RE (maybe due to changes/upgrades of the csv.read packages used there).

**Comment by Incei** [comment]
Yes I have seen it, strange that only these URL's had double quotes around them.
