### ISSUE TITLE
New data for hyperforin, digoxin, verapamil, dabigatran, rosuvastatin, gemfibrozil and probenecid and data corrections

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/Database-for-observed-data#82]
The database was expanded by data for hyperforin, digoxin, verapamil, dabigatran, rosuvastatin, gemfibrozil and probenecid (IDs 16201 - 16923). Furthermore, few errors in previously existing data for verapamil and digoxin were corrected.

**Comment by Yuri05** [comment]
Fixed with #81
